# 파이썬을 이용한 데이터 분석 


### 통계 처리와 scipy

In [1]:
# 통계량의 계산이나 기본적인 데이터 분석에 사용되는 함수는 scipy 패키지에 들어있음
import numpy as np
import scipy as sp

##소수점 이하 자릿수 
%precision 3

'%.3f'

### 1변량 데이터 관리

In [30]:
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])   # 물고기의 몸길이라는 1종류의 데이터 1변량 데이터
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

### 합계와 샘플 사이즈

In [31]:
# 합계
sp.sum(fish_data)

<ipython-input-31-ca24c36062ef>:2: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sp.sum(fish_data)


40

In [32]:
# 넘파이로 합계구하기 
np.sum(fish_data)

40

In [33]:
fish_data.sum()

40

In [34]:
sum(fish_data)

40

In [35]:
# 샘플사이즈 구하기
len(fish_data)

10

In [14]:
# 평균값
N = len(fish_data)
sum_value = sp.sum(fish_data)
mu = sum_value / N         # 데이터 총합 / 데이터 총 개수 = 평균
mu

<ipython-input-14-753e054c519b>:3: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sum_value = sp.sum(fish_data)


4.0

In [15]:
sp.mean(fish_data)

<ipython-input-15-0144c156ee1d>:1: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  sp.mean(fish_data)


4.0

In [36]:
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [16]:
# 표본분산 
sigma_2_sample = sp.sum((fish_data - mu) ** 2) / N    # 그림으로 설명하기 
sigma_2_sample

<ipython-input-16-81ec0b4183e2>:2: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sigma_2_sample = sp.sum((fish_data - mu) ** 2) / N


1.2

In [25]:
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [26]:
fish_data - mu                     # mu = 4 

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [27]:
(fish_data - mu) ** 2

array([4., 1., 1., 0., 0., 0., 0., 1., 1., 4.])

In [20]:
sp.sum((fish_data - mu) ** 2)    # 제곱의 총합 

<ipython-input-20-941c80e81f13>:1: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sp.sum((fish_data - mu) ** 2)


12.0

In [28]:
sp.sum((fish_data - mu) ** 2) /10     # 제곱의 총합을 샘플 사이즈로 나누기 

<ipython-input-28-ddede2b650f7>:1: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sp.sum((fish_data - mu) ** 2) /10


1.2

In [21]:
sp.var(fish_data, ddof = 0)               # sp.var를 사용하면 분산을 쉽게 구할수 있다.
                                        # 분산은 데이터가 흩어진 정도를 나타냄 

<ipython-input-21-89a2b1be993b>:1: DeprecationWarning: scipy.var is deprecated and will be removed in SciPy 2.0.0, use numpy.var instead
  sp.var(fish_data, ddof = 0)


1.2

### 불편분산

In [39]:
# 불편분산

sigma_2 = sp.sum((fish_data - mu) ** 2) / (N - 1)    #불편분산을 구할 시 n-1로 나누어 준다 
sigma_2

<ipython-input-39-c9de5246b77d>:3: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sigma_2 = sp.sum((fish_data - mu) ** 2) / (N - 1)    #불편분산을 구할 시 n-1로 나누어 준다


1.3333333333333333

In [40]:
sp.var(fish_data, ddof = 1)    # ddof = 1 인 경우 불편분산추정량을 이용한 경우임 

<ipython-input-40-9da7c973fe98>:1: DeprecationWarning: scipy.var is deprecated and will be removed in SciPy 2.0.0, use numpy.var instead
  sp.var(fish_data, ddof = 1)    # ddof = 1 인 경우 불편분산추정량을 이용한 경우임


1.3333333333333333

In [41]:
sigma = sp.sqrt(sigma_2)        # 표준편차 : 분산 데이터 측정 단위 제곱으로 표시 , 
                                 # 표준편차는 원데이터와 같은 측정단위로 분석하여 루트 씌어줌 
sigma

<ipython-input-41-762db3bd1f2b>:1: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  sigma = sp.sqrt(sigma_2)        # 표준편차 : 분산 데이터 측정 단위 제곱으로 표시 ,


1.1547005383792515

In [42]:
sp.std(fish_data, ddof = 1)  # 불편분산에 루트값을 취해서 표준편차 구할시 ddof = 1 꼭 넣어주기 !!

<ipython-input-42-3798bf3ae38d>:1: DeprecationWarning: scipy.std is deprecated and will be removed in SciPy 2.0.0, use numpy.std instead
  sp.std(fish_data, ddof = 1)  # 불편분산에 루트값을 취해서 표준편차 구할시 ddof = 1 꼭 넣어주기 !!


1.1547005383792515

In [43]:
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [44]:
fish_data - mu   # 표준화 하는 방법 _ 노트 참조 하기     표준화 : x -평균 / 표준편차 

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [45]:
fish_data - mu/sigma

array([-1.464, -0.464, -0.464,  0.536,  0.536,  0.536,  0.536,  1.536,
        1.536,  2.536])

In [29]:
sp.mean(standard)   #표준정규분포 평균 0 

0.000

In [30]:
sp.std(standard, ddof = 1)  #표준정규분포 표준편차 1

1.000

In [29]:
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [31]:
sp.amax(fish_data)   #최대값

6

In [32]:
sp.amin(fish_data)   #최소값

2

In [33]:
sp.median(fish_data)    #중앙값   (4+4)/2

4.000

In [34]:
fish_data_2 = np.array([2,3,3,4,4,4,4,5,5,100])

In [35]:
sp.mean(fish_data_2)

13.400

In [36]:
sp.median(fish_data_2) #(4+4)/2

4.000

In [46]:
from scipy import stats

In [47]:
fish_data_3 = np.array([1,2,3,4,5,6,7,8,9])
stats.scoreatpercentile(fish_data_3, 25)   # 사분위수 구하기 stats.scoreatpercentile  25% 

3.0

In [48]:
stats.scoreatpercentile(fish_data_3, 75)  # 사분위수 구하기 stats.scoreatpercentile  75%

7.0

In [49]:
stats.scoreatpercentile(fish_data_3, 50)

5.0