# 넘파이 시작

>넘파이의 기반 데이터 타입은 ndarray
ndarray를 이용해 넘파이에서 다차워 배열을 쉽게 생성하고 다양한 연산 수행가능

In [5]:
import numpy as np #넘파이 임포트 as의 의미는 사용할때 마다 numpy라고 쓰면 불편하니까 줄여서 쓰겠다라고 정의해주는 것

## array()
>넘파이의 array()함수는 파이썬 리스트와 같은 다양한 인자를 입력 받아 ndarray로 변환해준다.
ndarray 배열의 shape변수는 ndarray의 크기, 즉 행과 열의 수를 튜플로 가지고 있어서 ndarray배열의 차원까지 알 수 있다

In [11]:
arr1 = np.array([1,2,3]) # 1차원
print(type(arr1)) # arr1의 타입
print(arr1.shape) # arr1의 모양(차원)

<class 'numpy.ndarray'>
(3,)


In [12]:
arr2 = np.array([[1,2,3],
                 [2,3,4]]) # 2차원
print(type(arr2)) # arr2의 타입
print(arr2.shape) # arr2의 모양(차원)

<class 'numpy.ndarray'>
(2, 3)


In [13]:
arr3 = np.array([[1,2,3]]) # 이렇게 써도 2차원
print(type(arr3))
print(arr3.shape)

<class 'numpy.ndarray'>
(1, 3)


In [28]:
arr4 = np.array([[[ 0, 1], [ 2, 3], [ 4, 5]], 
                 [[ 6, 7], [ 8, 9], [10, 11]], 
                 [[12, 13], [14, 15], [16, 17]],
                 [[18, 19], [20, 21], [22, 23]]]) # 3차원

arr4.shape

3

###  차원이 다른 데이터를 입출력 변환을 하면 오류가 난다!

In [27]:
print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원, array4:{:3}차원'.format(arr1.ndim, arr2.ndim, arr3.ndim, arr4.ndim))

array1:1차원, array2:2차원, array3: 2차원, array4:  3차원


### [ ] : 1차원, [[ ]] : 2차원 [[[ ]]] : 3차원 ..... / ndim은 차원을 알려준다.
### ndarray내의 데이터값은 숫자 문자 다 가능함.
### 같은 데이터 타입만 가능하다, 즉 ndarray안에 int와 float 같이 못씀
### 속성은 dtype로 확인가능

In [6]:
list1 = [1,2,3]
print(type(list1)) # 리스트
arr1 = np.array(list1) # 리스트를 ndarray로 변환
print(type(arr1)) # 타입 출력
print(arr1, arr1.dtype) # 속성 데이터타입 출력

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [3]:
a = True
type(a)

bool

### 만약 데이터 타입이 섞이면 가장 큰 데이터타입으로 형변환을 일괄 적용한다.

In [9]:
list2 = [1,2,'test']
arr2 = np.array(list2)
arr2.dtype

dtype('<U11')

In [33]:
list3 = [1,2,3.0]
arr3 = np.array(list3)
print(arr3, arr3.dtype)

[1. 2. 3.] float64


### 데이터값의 타입변경은 astype()으로 가능

In [34]:
array_int = np.array([1, 2, 3]) #int생성
array_float = array_int.astype('float64') #float로 변경
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [35]:
array_int1 = array_float.astype('int32') #int로변경
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [36]:
array_float1 = np.array([1.1,2.1,3.1]) #float
array_int2 = array_float1.astype('int32') #int로변경
print(array_int2, array_int2.dtype)

[1 2 3] int32


### ndarray 편하게 생성하려면 arange, zeros, ones 를 잘 활용해야함.
### arange()는 순차적으로 데이터값으로 변환.
### 기본형식 = np.arange(시작값, 끝값, 어떤간격(step))
### 시작값이 생략되면 0부터 시작하고 step이 생략되면 기본값인 1이 들어간다

In [10]:
seq = np.arange(1,10) # 시작값이 생략되어있다. 생략되면 0부터 setp도 생략 1이 들어감
#0~10 까지 1간격으로 생성 / 10은 포함안된다.
print(seq)
print(seq.dtype, seq.shape) #seq의 type과 모양 알려줌

[1 2 3 4 5 6 7 8 9]
int32 (9,)


### zeros()는 함수 인자로 shape 값을 입력하면 모든 값을 0으로 채워준다.
### 기본형식 : np.zeros((모양), dtype='데이터타입')

In [39]:
ze = np.zeros((3,2), dtype='int32') # 3행2열 모양으로 만들고 0으로 채워준다. 타입은 int32
print(ze)
print(ze.dtype, ze.shape) # type과 shape 출력 / 처음에 적어준 모양대로 shape값이 출력된다.

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [40]:
a = np.zeros((3,2)) #dtype생략하면 int로 자동설정된다.
print(ze.dtype)

int32


### ones()는 zeros와 똑같으나 0대신 1로 채워서 만들어준다.

In [41]:
one = np.ones((3,2))
print(one)
print(one.dtype, one.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### np.empty() 쓰레기값으로 초기화 해준다.

In [53]:
k = np.empty((3,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


### np.full() 은 지정된 값으로 채워준다

In [56]:
b = np.full((3,5),7) # 3행5열을 7로 다채워!
print(b)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


### np.eye() 는 단위행렬을 만들어준다.
### 단위행렬? A행렬 X 단위행렬 = A 
### 어떤 행렬과 곱하면 자기자신이 나온다

In [60]:
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### np.linspace() : arange와 유사하지만 균등한 간격을 둔 시퀸스 생성
### 기본형식 : np.linspace(start, stop, num, endpoint, dtype)
#### start : 시작값
#### stop : 마지막값
#### num : 전체 갯수 / 기본값은 50이다
#### endpoin : stop값을 포함시킬지
#### dtype : type을 지정

In [64]:
a = np.linspace(1, 10, 4, endpoint=False) # 10 포함 x
print(a)

b = np.linspace(1, 10 , 4, endpoint=True) # 10 포함 o
print(b)

[1.   3.25 5.5  7.75]
[ 1.  4.  7. 10.]


### random 써서 ndarray 만들기

In [12]:
np.random.rand(4,5,3) # 0~1 사이에 분포로 랜덤한 ndarray 생성

array([[[0.88387405, 0.02557828, 0.64258956],
        [0.74533272, 0.59711451, 0.11956338],
        [0.99585705, 0.42997101, 0.92622113],
        [0.87140547, 0.42523316, 0.38141891],
        [0.19310873, 0.69360337, 0.56672521]],

       [[0.95004793, 0.44578306, 0.75150674],
        [0.71019721, 0.63286259, 0.95826963],
        [0.21276196, 0.01708355, 0.53271069],
        [0.4522597 , 0.98687426, 0.96209366],
        [0.14478066, 0.06732973, 0.43799458]],

       [[0.55353089, 0.04479332, 0.31578532],
        [0.13806708, 0.23436765, 0.68259531],
        [0.40850702, 0.0862441 , 0.42327164],
        [0.50066659, 0.87662943, 0.67507183],
        [0.26340366, 0.06727427, 0.53806156]],

       [[0.70914135, 0.23920355, 0.00377609],
        [0.06348479, 0.54330751, 0.57159103],
        [0.26654441, 0.27983524, 0.51396562],
        [0.27613386, 0.59221157, 0.53521823],
        [0.77847861, 0.78516016, 0.6343229 ]]])

### randn 함수
### n = 정규분포
### 정규분포로 샘플링된 랜덤 ndarray 생성

In [13]:
np.random.randn(5)

array([ 1.13207842,  1.09749716, -1.4171171 ,  1.8417992 , -0.17318822])

In [14]:
np.random.randn(3, 4, 2)

array([[[ 0.89651894, -1.4133683 ],
        [-0.38151104, -0.37371451],
        [-0.79749611, -0.88531562],
        [-1.38614207, -1.70291762]],

       [[-0.6139104 , -1.12055672],
        [-0.89797542,  0.21901616],
        [-0.18746359, -0.43663057],
        [-1.00989619,  0.56085446]],

       [[ 0.30493073,  1.46559685],
        [-0.15003833, -0.45986577],
        [ 1.24656084,  0.30093946],
        [ 1.25452429,  0.05954225]]])

### randint 함수
### 특정 정수 사이에서 랜덤하게 샘플링

In [16]:
np.random.randint(1, 100, size=(5,)) # 1~100 사이 1차원으로

array([20, 66, 91, 47, 71])

### seed함수
### 랜덤한 값을 동일하게 다시 생성하고자 할 때

In [17]:
np.random.seed(23)
np.random.randn(3,4)

array([[ 0.66698806,  0.02581308, -0.77761941,  0.94863382],
       [ 0.70167179, -1.05108156, -0.36754812, -1.13745969],
       [-1.32214752,  1.77225828, -0.34745899,  0.67014016]])

### choice
### 주어진 1차원 ndarray로 부터 랜덤하게 샘플링
### 정수가 주어진 경우, np.arange(해당숫자)

In [20]:
np.random.choice(100, size=(3,4)) #정수가 주어진 경우 0~100 사이라고 간주

array([[83, 58, 25, 66],
       [74, 35, 96, 56],
       [13, 60, 22, 38]])

In [21]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size=(2,2), replace=False)

array([[2. , 1.5],
       [2.6, 3. ]])

### 확률분포에 따른 ndarray 생성
### uniform
### normal 등등... 몰라도 되긴함 그냥 있다정도마?

In [22]:
np.random.uniform(1.0, 3.0, size=(4,5))

array([[2.26833065, 2.84085397, 1.26336399, 2.67879335, 2.40971945],
       [2.93578399, 2.80844986, 1.58561196, 1.29487279, 1.28251   ],
       [2.9085976 , 1.00084711, 1.58142383, 1.97754057, 1.05987474],
       [2.75684919, 1.22128512, 2.40958431, 1.05439985, 1.379564  ]])

In [23]:
np.random.normal(size=(3,4))
np.random.randn(3,4)

array([[-1.05613798,  0.82083419,  2.63419759, -0.0901257 ],
       [-1.85951523, -1.30404589, -2.60154296, -0.32092369],
       [ 0.94574687, -1.34668195, -0.89885805,  1.0212697 ]])

<hr>

### reshape() 특정 차원 및 크기로 변환해준다.

In [49]:
arr1 = np.arange(10) # 0~10까지 생성
print('arr1:\n',arr1)
print()

arr2 = arr1.reshape(2, 5) # arr1의 모양을 2행 5열로 바꿈
print('arr2:\n' ,arr2)
print()

arr3 = arr1.reshape(5, 2) # arr1의 모양을 5행 2열로 바꿈
print('arr3:\n', arr3)

arr1:
 [0 1 2 3 4 5 6 7 8 9]

arr2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

arr3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


###  reshape 꿀팁 ! 
### 원래 데이터의 갯수 = reshape안에 들어있는 숫자의 곱과 같아야한다
### -1을 활용 잘해야함
### reshape(2,5) 와 reshape(-1,5)와 같다.
### -1을 적으면 numpy가 알아서 맞춰준다

In [11]:
arr1 = np.arange(10)
print('arr1:\n',arr1)
print()

arr2 = arr1.reshape(-1, 5)
print('arr2:\n' ,arr2)
print()

arr3 = arr1.reshape(2, -1)
print('arr3:\n', arr3)

arr1:
 [0 1 2 3 4 5 6 7 8 9]

arr2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

arr3:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [67]:
#에러나는거 보여줌

arr1 = np.arange(10)
arr4 = arr1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

### 보통 (-1,1) 많이쓴다. 원본이 어떤 형태라도 2차원이고, 무조건 1개의 칼럼을 가진 친구로 변환해줌

In [76]:
arr1 = np.arange(8)
arr3d = arr1.reshape((2,2,2)) # 3차원으로 변경
print('arr3d:\n',arr3d.tolist())# tolist는 리스트로 변환해주는 함수이다.
print('arr3d shape:', arr3d.shape)
print()
# 3차원 ndarray를 2차원 ndarray로 변환
arr5 = arr3d.reshape(-1, 1)
print('arr5:\n',arr5.tolist())
print('arr5 shape:', arr5.shape)
print()

# 1차원 ndarray를 2차원 ndarray로 변환
arr6 = arr1.reshape(-1, 1)
print('arr6:\n', arr6.tolist())
print('arr6 shape:', arr6.shape)
#괄호를 잘보자!!!!!

arr3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
arr3d shape: (2, 2, 2)

arr5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
arr5 shape: (8, 1)

arr6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
arr6 shape: (8, 1)


###  flatten()
### 다차원 배열을 1차원으로 변경해준다.
### 이친구는 쓰면 원본데이터를 안건들인다.
### C => row 우선변경, F => column 우선변경

In [13]:
y = np.arange(15).reshape(3,5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [14]:
t2 = y.flatten(order='C')
print(t2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


###  ravel
### 이친구도 1차원으로 변경이긴한데
### 얘는 쓰면 원본데이터가 바뀌어버림
### C랑 F도 위에 친구랑 같다

In [5]:
x = np.arange(15).reshape(3,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [6]:
np.ravel(x, order='F') #방법 1

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [10]:
temp = x.ravel() # 방법 2
print(temp)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])