## 인덱싱

### 인덱싱이랑 슬라이싱은 너무 중요해

### 단일 값 추출

In [2]:
import numpy as np

In [3]:
# 1부터 9까지의 1차원 ndarray 생성
arr1 = np.arange(start=1, stop=10)
print('arr1:',arr1)

arr1: [1 2 3 4 5 6 7 8 9]


In [4]:
# index는 0부터 시작하므로 arr1[2]는 3번째 index 위치의 데이터값을 의미
value = arr1[2]
print('value: ', value)
print(type(value))

value:  3
<class 'numpy.int32'>


### 인덱스로 - 사용하기
### -1은 맨뒤의 값을 의미하고 -2는 맨뒤에서 두 번째 있는 값을 의미

In [5]:
print('맨 뒤의 값:',arr1[-1], '맨 뒤에서 두 번째 값:',arr1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


### 다차원 ndarray에서 인덱싱은 원하는 값의 위치를 적어준다. [3,3] 이런식

In [3]:
arr1d = np.arange(1,10)
arr2d = arr1d.reshape(3,3)
print(arr2d)
print()
print('(row=0, col=0) index 가리키는 값:', arr2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', arr2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', arr2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', arr2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


### 그냥 외우기
### axis 0은 row(행)
### axis 1은 column(열)
### axis 2는 heigh(높이) -> 3차원
### axis가 생략되면 axis 0을 의미한다

<hr>

## 슬라이싱
### 중요함...

###  : 를 써서 슬라이싱 가능
### [시작 : 끝]

In [10]:
arr1 = np.arange(1, 10)
arr3 = arr1[0:3]
print(arr3)
print(type(arr3))

[1 2 3]
<class 'numpy.ndarray'>


### : 기호 앞뒤로 생략해도 가능함
### 앞을 생략하면 0이 들어감(맨 처음 인덱스)
### 뒤를 생략하면 0이 들어감(맨 마지막 인덱스)
### 둘다 생략하면 처음부터 끝까지를 의미 (모든 인덱스)

In [11]:
arr1 = np.arange(1, 10)
arr4 = arr1[:3]
print(arr4)
print()

arr5 = arr1[3:]
print(arr5)
print()

arr6 = arr1[:]
print(arr6)

[1 2 3]

[4 5 6 7 8 9]

[1 2 3 4 5 6 7 8 9]


###  2차원 슬라이싱

In [4]:
arr1d = np.arange(1, 10)
arr2d = arr1d.reshape(3, 3)
print('arr2d:\n', arr2d)
print()

print('arr2d [0:2, 0:2]\n', arr2d[0:2, 0:2])
print()
print('arr2d [1:3, 0:3]\n', arr2d[1:3, 0:3])
print()
print('arr2d [1:3, :]\n', arr2d[1:3, :])
print()
print('arr2d [:, :]\n', arr2d[:,:])
print()
print('arr2d [:2,1:]\n', arr2d[:2,1:])
print()
print('arr2d [:2, 0]\n',arr2d[:2, 0])


arr2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

arr2d [0:2, 0:2]
 [[1 2]
 [4 5]]

arr2d [1:3, 0:3]
 [[4 5 6]
 [7 8 9]]

arr2d [1:3, :]
 [[4 5 6]
 [7 8 9]]

arr2d [:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

arr2d [:2,1:]
 [[2 3]
 [5 6]]

arr2d [:2, 0]
 [1 4]
arr2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

arr2d [0:2, 0:2]
 [[1 2]
 [4 5]]

arr2d [1:3, 0:3]
 [[4 5 6]
 [7 8 9]]

arr2d [1:3, :]
 [[4 5 6]
 [7 8 9]]

arr2d [:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

arr2d [:2,1:]
 [[2 3]
 [5 6]]

arr2d [:2, 0]
 [1 4]


###  2차원에서 뒤에오는 인덱스 없애면 1차원 반환

In [21]:
print(arr2d[0])
print(arr2d[1])
print('arr2d[9] shape:', arr2d[0].shape, 'arr2d[1] shape:', arr2d[1].shape)

[1 2 3]
[4 5 6]
arr2d[9] shape: (3,) arr2d[1] shape: (3,)


### 팬시 인덱싱

In [23]:
arr1d = np.arange(1, 10)
arr2d = arr1d.reshape(3, 3)

arr3 = arr2d[[0, 1], 2]
print('arr2d[[0, 1], 2] => ', arr3.tolist())

arr4 = arr2d[[0, 1], 0:2]
print('arr2d[[0, 1], 0:2] => ', arr4.tolist())

arr5 = arr2d[[0,1]]
print('arr2d[[0,1]] => ', arr5.tolist())

arr2d[[0, 1], 2] =>  [3, 6]
arr2d[[0, 1], 0:2] =>  [[1, 2], [4, 5]]
arr2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱
### 조건으로 필터링하기 때문에 매우 자주쓴다!

In [5]:
arr1d = np.arange(1, 10)
arr1d > 5
# [ ] 안에 arr1d > 5 불린 인덱싱 적용
arr3 = arr1d[arr1d > 5]
print('arr1d > 5 불린 인덱싱 결과 값 :', arr3)

arr1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [25]:
arr1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [27]:
boolean_index = np.array([False, False, False, False, False,  True,  True,  True,  True])
arr3 = arr1d[boolean_index]
print('불린 인덱스로 필터링 결과:', arr3)

불린 인덱스로 필터링 결과: [6 7 8 9]
