### 행렬의 정렬
### sort()
### sort() 호출방법은 여러가지가 있다.
### np.sort => 넘파이에서 호출 (원 행렬 그대로 유지함)
### ndarray.sort() => 행렬 자체에서 호출 (원 행렬을 정렬해버림)

In [2]:
import numpy as np

In [5]:
org_arr = np.array([3,1,9,5])
print('원본 행렬:', org_arr)
print()
# np.sort()로 정렬
sort_arr1 = np.sort(org_arr)
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_arr1)
print('np.sort() 호출 후 원본 행렬:', org_arr)
print()

sort_arr2 = org_arr.sort()
print('org_arr.sort() 호출 후 반환된 행렬:', sort_arr2)
print('org_arr.sort9) 호출 후 원본 행렬:', org_arr)

원본 행렬: [3 1 9 5]

np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]

org_arr.sort() 호출 후 반환된 행렬: None
org_arr.sort9) 호출 후 원본 행렬: [1 3 5 9]


### sort()를 하면 기본적으로 오름차순으로 정렬한다.
### 내림차순으로 정렬하려면 [::-1] 사용

In [7]:
sort_arr1_desc = np.sort(org_arr)[::-1]
print('내림차순으로 정렬:', sort_arr1_desc)

내림차순으로 정렬: [9 5 3 1]


### 2차원 이상일경우 axis로 행 렬 방향 정렬이 가능함

In [8]:
arr2d = np.array([[8, 12],
                 [7,1]])

sort_arr2d_axis0 = np.sort(arr2d, axis=0)
print('로우 방향으로 정렬:\n', sort_arr2d_axis0)
print()

sort_arr2d_axis1 = np.sort(arr2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_arr2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]

컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


### 정렬된 행렬의 인덱스가 알고싶다면?
### np.argsort()를 쓴다!
### 반환은 ndarray로 된다

In [3]:
org_arr = np.array([3,1,9,5])
sort_in = np.argsort(org_arr)
print(type(sort_in))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_in)
print(org_arr)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
[3 1 9 5]


### 오름차순이 아닌 내림차순으로 졍렬 시 앞에서와 똑같이 [::-1] 붙여준다

In [11]:
org_arr = np.array([3,1,9,5])
sort_in_desc = np.argsort(org_arr)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_in_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]
