## numpy・pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
sample_list = [1,2,3,4,5]
sample_list

[1, 2, 3, 4, 5]

In [3]:
sample_array = np.array([1,2,3,4,5])
sample_array

array([1, 2, 3, 4, 5])

In [4]:
sample_array + 2

array([3, 4, 5, 6, 7])

In [5]:
sample_array * 2

array([ 2,  4,  6,  8, 10])

In [6]:
np.array([1 ,2, "A"])

array(['1', '2', 'A'], dtype='<U11')

In [7]:
sample_array_2 = np.array(
    [[1,2,3,4,5],
     [6,7,8,9,10]])
sample_array_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
sample_array_2.shape

(2, 5)

In [9]:
np.arange(start = 1, stop = 6, step = 1)

array([1, 2, 3, 4, 5])

In [10]:
np.arange(start = 0.1, stop = 0.8, step = 0.2)

array([0.1, 0.3, 0.5, 0.7])

In [11]:
np.arange(0.1, 0.8, 0.2)

array([0.1, 0.3, 0.5, 0.7])

In [12]:
np.tile("A", 5)

array(['A', 'A', 'A', 'A', 'A'], dtype='<U1')

In [13]:
np.tile(0, 4)

array([0, 0, 0, 0])

In [14]:
np.zeros(4)

array([0., 0., 0., 0.])

In [15]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
d1_array = np.array([1,2,3,4,5])
d1_array

array([1, 2, 3, 4, 5])

In [18]:
d1_array[0]

1

In [19]:
d1_array[1:3]

array([2, 3])

In [20]:
d2_array = np.array(
    [[1,2,3,4,5],
    [6,7,8,9,10]])
d2_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
d2_array[0, 3]

4

In [22]:
d2_array[1, 2:4]

array([8, 9])

In [23]:
sample_df = pd.DataFrame({
    'col1' : sample_array, 
    'col2' : sample_array * 2,
    'col3' : ["A", "B", "C", "D", "E"]
})
print(sample_df)

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E


In [24]:
sample_df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

In [25]:
file_data = pd.read_csv("2-4-1-sample_data.csv")
print(file_data)

   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C


In [26]:
type(file_data)

pandas.core.frame.DataFrame

In [27]:
df_1 = pd.DataFrame({
    'col1' : np.array([1, 2, 3]),
    'col2' : np.array(["A", "B", "C"])
})
df_2 = pd.DataFrame({
    'col1' : np.array([4, 5, 6]),
    'col2' : np.array(["D", "E", "F"])
})

In [28]:
print(pd.concat([df_1, df_2]))

   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F


In [29]:
print(pd.concat([df_1, df_2], axis = 1))

   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F


In [30]:
print(sample_df)

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E


In [31]:
print(sample_df.col2)

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int32


In [32]:
print(sample_df["col2"])

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int32


In [33]:
print(sample_df[["col2", "col3"]])

   col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E


In [34]:
print(sample_df.drop("col1", axis = 1))

   col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E


In [36]:
print(sample_df.head(n = 4))

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D


In [37]:
print(sample_df.query('index == 0'))

   col1  col2 col3
0     1     2    A


In [38]:
print(sample_df.query('col3 == "A"'))

   col1  col2 col3
0     1     2    A


In [39]:
print(sample_df.query('col3 == "A"')[["col2", "col3"]])

   col2 col3
0     2    A


In [40]:
type(sample_df)

pandas.core.frame.DataFrame

In [41]:
type(sample_df.col1)

pandas.core.series.Series

In [42]:
type(np.array(sample_df.col1))

numpy.ndarray

In [43]:
type(sample_df.col1.values)

numpy.ndarray