In [2]:
import numpy as np
import scipy as sp

#소수점 이하 자릿수
%precision 3

'%.3f'

In [4]:
fish_data = np.array([2,3,3,4,4,4,4,5,5,6]) # 물고기의 몸길이라는 1종류의 데이터 1변량 데이터
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

# 합계와 샘플 사이즈 

In [5]:
#합계
sp.sum(fish_data)

<ipython-input-5-cdcd498b291c>:2: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sp.sum(fish_data)


40

In [6]:
#넘파이로 합계구하기
np.sum(fish_data)

40

In [7]:
#샘플사이즈 구하기
len(fish_data)

10

In [8]:
#평균값
N = len(fish_data)
sum_value = sp.sum(fish_data)
mu = sum_value / N #데이터 총합 / 데이터 총 개수 = 평균
mu

<ipython-input-8-a1d74763c002>:3: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sum_value = sp.sum(fish_data)


4.0

In [9]:
sp.mean(fish_data)

<ipython-input-9-0144c156ee1d>:1: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  sp.mean(fish_data)


4.0

In [10]:
#표본분산
sigma_2_sample = sp.sum((fish_data - mu) **2) / N
sigma_2_sample

<ipython-input-10-6251545dacf1>:2: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sigma_2_sample = sp.sum((fish_data - mu) **2) / N


1.2

In [11]:
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [12]:
fish_data - mu #평균 빼기

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [15]:
(fish_data - mu) ** 2 #뺸 값 제곱

array([4., 1., 1., 0., 0., 0., 0., 1., 1., 4.])

In [16]:
sp.var(fish_data, ddof=0) #sp.var를 사용하면 분산을 쉽게 구할 수 있다.
# 분산은 데이터가 흩어진 정도를 나타냄

<ipython-input-16-b89f63614955>:1: DeprecationWarning: scipy.var is deprecated and will be removed in SciPy 2.0.0, use numpy.var instead
  sp.var(fish_data, ddof=0) #sp.var를 사용하면 분산을 쉽게 구할 수 있다.


1.2

# 불편분산 

In [17]:
#불편분산
sigma_2 = sp.sum((fish_data - mu) ** 2) / (N - 1) #불편분산을 구할 시 n-1로 나누어준다
sigma_2

<ipython-input-17-9cfd991b61da>:2: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sigma_2 = sp.sum((fish_data - mu) ** 2) / (N - 1) #불편분산을 구할 시 n-1로 나누어준다


1.3333333333333333

In [23]:
sp.var(fish_data, ddof=1) #ddof = 1인 경우 불편분산추정량을 이용한 경우임

<ipython-input-23-e45898ee4825>:1: DeprecationWarning: scipy.var is deprecated and will be removed in SciPy 2.0.0, use numpy.var instead
  sp.var(fish_data, ddof=1) #ddof = 1인 경우 불편분산추정량을 이용한 경우임


1.3333333333333333

In [24]:
sigma = sp.sqrt(sigma_2) # 표준편차 : 분산 데이터 측정 단위 제곱으로 표시
sigma  # 표준편차는 원데이터와 같은 측정단위로 분석하여 루트 씌어줌

<ipython-input-24-d67241efa134>:1: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  sigma = sp.sqrt(sigma_2) # 표준편차 : 분산 데이터 측정 단위 제곱으로 표시


1.1547005383792515

In [25]:
sp.std(fish_data, ddof=1) # 불편분산에 루트값을 취해서 표준편차 구할시 ddof=1 꼭 넣어주기!!!!

<ipython-input-25-4eca570e8ff0>:1: DeprecationWarning: scipy.std is deprecated and will be removed in SciPy 2.0.0, use numpy.std instead
  sp.std(fish_data, ddof=1) # 불편분산에 루트값을 취해서 표준편차 구할시 ddof=1 꼭 넣어주기!!!!


1.1547005383792515

In [26]:
fish_data - mu # 표준화 하는 방법 ///////////// 표준화 : x-평균 / 표준편차

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [32]:
fish_data - mu/sigma

array([-1.464, -0.464, -0.464,  0.536,  0.536,  0.536,  0.536,  1.536,
        1.536,  2.536])

In [34]:
sp.mean(standard) # 표준정규분포 평균 0

<ipython-input-34-d1c2004da3bd>:1: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  sp.mean(standard) # 표준정규분포 평균 0


0.0

In [36]:
sp.std(standard, ddof = 1)  # 표준정규분포 표준편차 1

<ipython-input-36-57a9aa8913c4>:1: DeprecationWarning: scipy.std is deprecated and will be removed in SciPy 2.0.0, use numpy.std instead
  sp.std(standard, ddof = 1)  # 표준정규분포 표준편차 1


1.1547005383792515

In [37]:
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [39]:
sp.amax(fish_data) #최대값

<ipython-input-39-ab9f4ecb7eca>:1: DeprecationWarning: scipy.amax is deprecated and will be removed in SciPy 2.0.0, use numpy.amax instead
  sp.amax(fish_data) #최대값


6

In [40]:
sp.amin(fish_data) # 최소값

<ipython-input-40-c54bed42fc2e>:1: DeprecationWarning: scipy.amin is deprecated and will be removed in SciPy 2.0.0, use numpy.amin instead
  sp.amin(fish_data) # 최소값


2

In [41]:
sp.median(fish_data) # 중앙값(4+4)/2

<ipython-input-41-4bdf8b9edfe0>:1: DeprecationWarning: scipy.median is deprecated and will be removed in SciPy 2.0.0, use numpy.median instead
  sp.median(fish_data) # 중앙값(4+4)/2


4.0

In [44]:
fish_data_2 = np.array([2,3,3,4,4,4,4,5,5,100])

In [45]:
sp.mean(fish_data_2)

<ipython-input-45-6bc7cbd09eab>:1: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  sp.mean(fish_data_2)


13.4

In [46]:
sp.median(fish_data_2)

<ipython-input-46-d46825e1bd76>:1: DeprecationWarning: scipy.median is deprecated and will be removed in SciPy 2.0.0, use numpy.median instead
  sp.median(fish_data_2)


4.0

In [47]:
from scipy import stats #4분위수 구하려면 이렇게 해야함

In [48]:
fish_data_3 = np.array([1,2,3,4,5,6,7,8,9])
stats.scoreatpercentile(fish_data_3, 25) # 사분위수 구하기 stats.scoreatpercentile 25 %

3.0

In [49]:
stats.scoreatpercentile(fish_data_3,75) # 사분위수 구하기 stats.scoreatpercentile 75%

7.0

In [50]:
stats.scoreatpercentile(fish_data_3, 50)

5.0