In [110]:
import numpy as np # numpy 불러오기
arr1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31]) # numpy array 함수 사용
print(arr1)

[ 2  3  5  7 11 13 17 19 23 29 31]


In [111]:
type(arr1)

numpy.ndarray

In [112]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #2차원

In [113]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [114]:
type(arr2)

numpy.ndarray

In [115]:
arr2.shape

(3, 4)

In [116]:
arr1.size #사이즈 확인

11

In [117]:
arr2.size 

12

In [118]:
import numpy as np # numpy 불러오기
arr1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31]) # numpy array 함수 사용, 인덱싱

In [119]:
arr1[0]

2

In [120]:
arr1[5]

13

In [121]:
arr1[-1]

31

In [122]:
arr1[[1,3,4]]

array([ 3,  7, 11])

In [123]:
arr2 = np.array([2, 1, 3])

In [124]:
arr2

array([2, 1, 3])

In [125]:
arr1[arr2] #numpy array로 인덱스 값 불러오기

array([5, 3, 7])

In [126]:
arr1[2:7] #슬라이싱 2번 인덱스부터 (7-1)번 인덱스까지 불러오기

array([ 5,  7, 11, 13, 17])

In [127]:
arr1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [128]:
arr1[2:6:3] # 2번부터 (6-1)번 인덱스까지 숫자 3개 건너뛰기

array([ 5, 13])

# 기본연산
> numpy array는 모든 연산이 가능하다

In [129]:
arr1 = np.arange(10)
arr2 = np.arange(10,20)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [131]:
arr1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [132]:
arr1 /2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [133]:
arr1 +2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [134]:
arr1 **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [135]:
arr1 = arr1+2

In [136]:
arr1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [137]:
arr1 > 4

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [138]:
arr1 % 2 == 0 

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

# 참/거짓 연산 

In [139]:
booleans = np.array([True,True,True,True, False,False,True])

In [140]:
np.where(booleans) #해당하는 값만 출력 (False값에 해당하면 안나온다.)

(array([0, 1, 2, 3, 6], dtype=int64),)

In [141]:
arr1 = np.arange(1,101) # 1~101사이의 모든 값 넣어준다.
print(arr1)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [142]:
arr = np.arange(3,101,3) # 3과 101 사이에서 3간격으로 만들어준다.
print(arr)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


# 문제풀기

#  엔화로 바꾸기

In [179]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

In [181]:
won = np.array(revenue_in_yen) * 10.08 # 리스트이기 때문에 넘파이 array로 바꾼다. 환율 적용하여 계산
won

array([3024000., 3427200., 3225600., 3628800., 4435200., 1411200.,
       1814400., 3427200., 3326400., 2923200., 2822400., 3830400.,
       1713600., 1411200., 2318400., 3931200., 4032000., 3528000.,
       3830400., 1512000., 1108800., 2419200., 3830400., 3830400.,
       3427200., 4233600., 1512000., 1310400., 3628800., 3225600.,
       2520000.])

# 달러와 엔 합치기

In [176]:
revenue_in_dollar = [
    1200, 1600, 1400, 1300, 
    2100, 1400, 1500, 2100, 
    1500, 1500, 2300, 2100, 
    2800, 2600, 1700, 1400, 
    2100, 2300, 1600, 1800, 
    2200, 2400, 2100, 2800, 
    1900, 2100, 1800, 2200, 
    2100, 1600, 1800
]

In [147]:
won = (np.array(revenue_in_dollar) * 1138) + (np.array(revenue_in_yen) * 10.08) # 달러와 엔을 합쳐준다. 환율 적용

In [217]:
won = won.astype(int) # int로 변환

In [218]:
print(won)

[3024000 3427200 3225600 3628800 4435200 1411200 1814400 3427200 3326400
 2923200 2822400 3830400 1713600 1411200 2318400 3931200 4032000 3528000
 3830400 1512000 1108800 2419200 3830400 3830400 3427200 4233600 1512000
 1310400 3628800 3225600 2520000]


# 20만엔 이상만 보고싶다. 

In [225]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

In [226]:
filt = np.where(yen <= 200000) #위에서 yen에 데이터를 넣어놨기 때문에 filter를 만들어준다. 이렇게하면 맞는 값의 인덱스만 저장된다.
filt

(array([ 5,  6, 12, 13, 19, 20, 26, 27], dtype=int64),)

In [222]:
yen[filt] # 앞에서 배웠던 불른과 같이 won[filt]를 하게되면 filt안에 들어있는 인덱스 값이 들어가게되고 인덱스 값에 맞는 값만 출력된다.

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])

# 데이터 타입 바꾸는 방법

In [227]:
yen = np.array(revenue_in_yen) # 엔 데이터를 넘파이 array로 변경
yen

array([300000, 340000, 320000, 360000, 440000, 140000, 180000, 340000,
       330000, 290000, 280000, 380000, 170000, 140000, 230000, 390000,
       400000, 350000, 380000, 150000, 110000, 240000, 380000, 380000,
       340000, 420000, 150000, 130000, 360000, 320000, 250000])

#  두번째 방법

In [229]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

In [230]:
yen = np.array(revenue_in_yen) # 엔 데이터를 넘파이 array로 변경

In [231]:
filter = yen <= 200000
filter

array([False, False, False, False, False,  True,  True, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False,  True,  True, False, False, False, False, False,  True,
        True, False, False, False])

In [232]:
yen[filter]

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])

# 세번째 방법

In [233]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

In [234]:
yen = np.array(revenue_in_yen) # 엔 데이터를 넘파이 array로 변경

In [235]:
yen[yen<= 200000]

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])

# 최대값 최솟값

In [240]:
import numpy as np

array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.max()) #최대값
print(array1.min()) #최솟값

31
5


# 평균

In [241]:
import numpy as np
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])
print(array1.mean()) #평균

15.25


# 중앙값

In [242]:
import numpy as np
array1 = np.array([8, 12, 9, 15, 16])
array2 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(np.median(array1)) #중앙값
print(np.median(array2)) #중앙값
#평균은 모든 수들을 더해서 나눠주고 중앙값은 진짜 숫자들의 중앙에 있는 값

12.0
13.5


# numpy로 행렬 만들기

In [1]:
import numpy as np # numpy불러오기

In [2]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])             #행렬을 만들기 위해 numpy의 array 메소드 사용(4X3 행렬)

In [3]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [4]:
B = np.array([
    [1, 2],
    [3, -4],
    [-5, 6]
])

In [5]:
B

array([[ 1,  2],
       [ 3, -4],
       [-5,  6]])

In [6]:
C = np.random.rand(3, 5) #행렬에 random값 넣어기, ()안에는 차원값을 넣어준다.

In [8]:
C

array([[4.51017609e-01, 9.89843980e-01, 9.68834294e-01, 2.99321163e-01,
        9.76763644e-04],
       [1.82285598e-01, 4.33489167e-02, 4.76171374e-01, 1.87990600e-01,
        8.06752766e-01],
       [8.15570376e-01, 6.47367359e-01, 1.18147300e-01, 1.45966930e-01,
        4.43998476e-01]])

In [9]:
D = np.zeros((2,4)) # 모든값이 0 인 행렬 만들때, ()안에 차원값 넣기

In [10]:
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [12]:
A[0][2]   #행렬 A의 1X3을 받아오고 싶을 때, Python은 0부터 시작한다.

2

# 문제

## 1. 4X3 행렬 A를 numpy array로 정의해보기

In [13]:
A = ([
    [1, 2, 3],
    [-1, 0, 2],
    [3, 4, 5],
    [2, -2, -3]
])
A

[[1, 2, 3], [-1, 0, 2], [3, 4, 5], [2, -2, -3]]

## 2. 3X2행렬 B를 numpy array로 정의해보기

In [14]:
B = ([
    [0, 2],
    [1, -2],
    [3, -4]
])
B

[[0, 2], [1, -2], [3, -4]]

## 정의한 행렬 A의 2행2열 원소 찾기 

In [15]:
A[1][1]

0

## 정의한 행렬 B의 3행 1열 원소 찾기

In [16]:
B[2][0]

3